**<p>Disciplina:** Métodos Numéricos</p>
**<p>Semestre:** 2020.2</p>
**<p>Aluno:** Jardel Brandon de Araujo Regis</p>
**<p>Mátricula:** 201621250014</p>
**<p>2ª Unidade:** Álgebra Linear Computacional</p>

---
# <center>Introdução aos Sistemas de Equações Lineares</center>
## <center>Exercícios #1 </center>
---

In [1]:
import numpy as np

### Introdução à sistemas de equações lineares 

$$
\begin{aligned}
3 x_{1}+4 x_{2}-5 x_{3}+x_{4} &=-10 \\
x_{2}+x_{3}-2 x_{4} &=-1 \\
4 x_{3}-5 x_{4} &=3 \\
2 x_{4} &=2
\end{aligned}
$$

#### Exercício 1.

Verifique, refazendo o exemplo acima, se a equação da substituição
retroativa, descrita na equação 20, de fato funciona.

$$
x_{i}=\frac{b_{i}-\sum_{j=i+1}^{n} a_{i j} x_{j}}{a_{i i}}, \quad \forall i=m, \ldots, 1 
$$

<center> 20. </center>



Resposta:

$x_{n}$, pode ser encontrada diretamente, simplesmente fazendo
\begin{equation}
a_{n n} x_{n}=b_{n} \Rightarrow x_{n}= \frac{b_{n}}{a_{n n}}
\end{equation} 

\begin{eqnarray}
x_{n} =& \frac{2}{2} \nonumber \\
x_{4} =& 1 \nonumber
\end{eqnarray}

Para a penúltima equação $, a_{(n-1)(n-1)} x_{n-1}+a_{(n-1) n} x_{n}=b_{n-1},$ o valor de uma incógnita já é conhecido, $x_{n}$. Dessa forma, para encontrar a incógnita que falta, basta isolar a incógnita
cujo valor ainda não se conhece

\begin{eqnarray}
{a}_{(n-1)(n-1)} x_{n-1}+a_{(n-1) n} x_{n}=b_{n-1} \Rightarrow x_{n-1}=\frac{b_{n-1}-a_{(n-1) n} x_{n}}{a_{(n-1)(n-1)}}
\end{eqnarray}
<br>
substituindo o valor de $x_{n}$ encontrado no passo anterior.
<br>
\begin{eqnarray}
x_{n-1} =& \frac{(3 - (- 5) * 1)}{4} \nonumber \\ 
x_{n-1} =& \frac{3 + 5}{4} \nonumber \\
x_{n-1} =& \frac{8}{4} \nonumber \\
x_{3} =& 2 \nonumber
\end{eqnarray}
<br>
<br>
<br>
\begin{eqnarray}
x_{n-2} =& \frac{(-1 - ((1 * 2) + (-2 * 1))}{1} \nonumber \\  
x_{n-2} =& \frac{-1}{1} \nonumber \\ 
x_{2} =& -1 \nonumber \\ 
\end{eqnarray}
<br>
<br>
<br>
\begin{eqnarray}
x_{n-3} =& \frac{-10 - ((4 * -1) + (-5 * 2) + (1 * 1))}{3} \nonumber \\ 
x_{x-3} =& \frac{-10 - (-4 -10 + 1}{3} \nonumber \\ 
x_{n-3} =& \frac{-10 - (-13)}{3} \nonumber \\ 
x_{n-3} =& \frac{-10 + 13)}{3} \nonumber \\ 
x_{n-3} =& \frac{3)}{3} \nonumber \\ 
x_{1} =& 1 \nonumber \\ 
\end{eqnarray}

Logo, <br>
\begin{eqnarray}
x_1 =& 1 \nonumber \\ 
x_2 =& -1 \nonumber \\ 
x_3 =& 2 \nonumber \\ 
x_4 =& 1 \nonumber \\ 
\end{eqnarray}

#### Exercício 2. 
Faça um programa em Python que calcule a solução de um sistema
triangular superior usando substituição retroativa. Para representação das matrizes e
vetores use exclusivamente Numpy.

In [2]:
def resolver_sistemas_lineares_triangulares(A, b, inferior=False):
    n = len(b)
    x = np.empty(n)
    if(inferior == True):
        x[0] = b[0] / A[0][0]
        for i in range(1, n):
            x[i] = (b[i] - np.sum(A[i][:i] * x[:i])) / A[i, i]
    else:
        x[-1] = b[-1] / A[-1][-1]
        for i in range(n - 2, -1, -1):
            x[i] = (b[i] - np.sum(A[i][i + 1:] * x[i + 1:])) / A[i][i]
    return x

In [3]:
A = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])

In [4]:
x = resolver_sistemas_lineares_triangulares(A, b)
x

array([ 1., -1.,  2.,  1.])

In [5]:
A.dot(x)

array([-10.,  -1.,   3.,   2.])

#### Exercício 3. 
Faça um programa em Python que calcule a solução de um sistema
triangular inferior usando substituição progressiva. Para representação das matrizes e
vetores use exclusivamente Numpy.

$$
\begin{array}{r}
3 x_{1}=4 \\
2 x_{1}+x_{2}=2 \\
x_{1}+x_{3}=4 \\
x_{1}+x_{2}+x_{3}+x_{4}=2
\end{array}
$$

In [6]:
A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
b = np.array([4,2,4,2])

In [7]:
x = resolver_sistemas_lineares_triangulares(A, b, True)
x

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [8]:
A.dot(x)

array([4., 2., 4., 2.])

#### Exercício 4.
Compare os resultados das implementações de suas funções para a solução
de sistemas triangulares com a função do scipy. Os resultados são diferentes? Experimente
com outros exemplos.

In [9]:
import scipy.linalg as sla
import numpy as np

$$
\begin{aligned}
3 x_{1}+4 x_{2}-5 x_{3}+x_{4} &=-10 \\
x_{2}+x_{3}-2 x_{4} &=-1 \\
4 x_{3}-5 x_{4} &=3 \\
2 x_{4} &=2
\end{aligned}
$$

In [10]:
A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])

In [11]:
x = sla.solve_triangular(A,b)
x

array([ 1., -1.,  2.,  1.])

In [12]:
y = resolver_sistemas_lineares_triangulares(A, b)
y

array([ 1., -1.,  2.,  1.])

In [13]:
print(np.array_equal(x, y))

True


$$
\begin{array}{r}
3 x_{1}=4 \\
2 x_{1}+x_{2}=2 \\
x_{1}+x_{3}=4 \\
x_{1}+x_{2}+x_{3}+x_{4}=2
\end{array}
$$

In [14]:
A = np.array([[3,0,0,0],[2,1,0,0],[1,0,1,0],[1,1,1,1]])
b = np.array([4,2,4,2])

In [15]:
x = sla.solve_triangular(A,b, lower=True)
x

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [16]:
y = resolver_sistemas_lineares_triangulares(A, b, True)
y

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [17]:
print(np.array_equal(x, y))

False


Outro Exemplo:
$$
\left\{\begin{aligned}
x_{1}+2 x_{2}+x_{3} &=20 \\
x_{2}+2 x_{3} &=11 \\
x_{3} &=3
\end{aligned}\right.
$$

In [18]:
A = np.array([[1, 2, 1], [0, 1, 2], [0, 0, 1]])
b = np.array([20, 11, 3])

In [19]:
x = sla.solve_triangular(A,b)
x

array([7., 5., 3.])

In [20]:
y = resolver_sistemas_lineares_triangulares(A, b)
y

array([7., 5., 3.])

In [21]:
print(np.array_equal(x, y))

True


Outro Exemplo:
$$
\left(\begin{array}{rrr}
2 & 1 & 3 \\
0 & -1 & 1 \\
0 & 0 & 1
\end{array}\right)\left(\begin{array}{l}
x_{1} \\
x_{2} \\
x_{3}
\end{array}\right)=\left(\begin{array}{l}
9 \\
1 \\
2
\end{array}\right)
$$

In [22]:
A = np.array([[2, 1, 3], [0, -1, 1], [0, 0, 1]])
b = np.array([9, 1, 2])

In [23]:
x = sla.solve_triangular(A,b)
x

array([1., 1., 2.])

In [24]:
y = resolver_sistemas_lineares_triangulares(A, b)
y

array([1., 1., 2.])

In [25]:
print(np.array_equal(x, y))

True


### Introdução à sistemas de equações lineares - Complemento

#### Exercício 1.1 
Classifique os sistemas abaixo com relação a quantidade e existência de
soluções.

##### a)
$$
\begin{array}{r}
x+2 y+3 z=1 \\
4 x+5 y+6 z=1 \\
7 x+8 y+9 z=1
\end{array}
$$

##### resolução a)

In [26]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9,]])
b = np.array([1, 1, 1])

In [27]:
np.linalg.matrix_rank(A)

2

In [28]:
 np.linalg.matrix_rank(np.c_[A, b])

2

In [29]:
A.shape[1]

3

Como o posto da matriz dos coeficientes é igual ao posto da matriz ampliada que são menores que o número de incógnitas: $P_C = P_A < número de incógnitas.
Logo o sistema possuí infinitas soluções (Possível e Inderteminados)

##### b)
$$
\begin{aligned}
2 x+3 y &=10 \\
-4 x-6 y &=-10
\end{aligned}
$$

##### resolução b)

In [30]:
A = np.array([[2, 3], [-4, -6]])
b = np.array([10, -10])

In [31]:
np.linalg.matrix_rank(A)

1

In [32]:
 np.linalg.matrix_rank(np.c_[A, b])

2

In [33]:
A.shape[1]

2

Como o posto da matriz dos coeficientes é menor que o posto da matriz ampliada: $P_C < P_A$.
Logo o sistema não tem solução (Impossível)

Exemplo 3.2
$$
\begin{aligned}
3 x_{1}+4 x_{2}-5 x_{3}+x_{4} &=-10 \\
x_{2}+x_{3}-2 x_{4} &=-1 \\
4 x_{3}-5 x_{4} &=3 \\
2 x_{4} &=2
\end{aligned}
$$

#### Exercício 1.2 
Repita o exemplo 3.2 acima, porém fazendo cada passo da execução de
forma explícita, comparando como o algoritmo 1.3 e a função sist_lin_tri_sup funcionam.
Sugestão: faça isso de forma manuscrita. Ajudará a entender melhor cada passo.


Algoritmo 1.3 Substituição retroativa para sistemas triangulares superiores
Entrada: matriz triangular superior de coeficientes $A,$ vetor de termos independentes $b$ Passo 1: criar um vetor com todos os valores iguais a zero: $x=0$ Passo 2: calcular a incógnita de maior índice $x_{n}=\frac{b_{n}}{a_{n n}}$ para $i$ variando de $n-1$ à 1 faça
Passo 3: calcular os valores restantes do vetor soluçāo
$$
x_{i}=\frac{b_{i}-\sum_{j=i+1}^{n} a_{i j} x_{j}}{a_{i i}}
$$
Passo 4: atualizar os valores do vetor $x$

Resposta:

$x_{n}$, pode ser encontrada diretamente, simplesmente fazendo
\begin{equation}
a_{n n} x_{n}=b_{n} \Rightarrow x_{n}= \frac{b_{n}}{a_{n n}}
\end{equation} 

\begin{eqnarray}
x_{n} =& \frac{2}{2} \nonumber \\
x_{4} =& 1 \nonumber
\end{eqnarray}

Para a penúltima equação $, a_{(n-1)(n-1)} x_{n-1}+a_{(n-1) n} x_{n}=b_{n-1},$ o valor de uma incógnita já é conhecido, $x_{n}$. Dessa forma, para encontrar a incógnita que falta, basta isolar a incógnita
cujo valor ainda não se conhece

\begin{eqnarray}
{a}_{(n-1)(n-1)} x_{n-1}+a_{(n-1) n} x_{n}=b_{n-1} \Rightarrow x_{n-1}=\frac{b_{n-1}-a_{(n-1) n} x_{n}}{a_{(n-1)(n-1)}}
\end{eqnarray}
<br>
substituindo o valor de $x_{n}$ encontrado no passo anterior.
<br>
\begin{eqnarray}
x_{n-1} =& \frac{(3 - (- 5) * 1)}{4} \nonumber \\ 
x_{n-1} =& \frac{3 + 5}{4} \nonumber \\
x_{n-1} =& \frac{8}{4} \nonumber \\
x_{3} =& 2 \nonumber
\end{eqnarray}
<br>
<br>
<br>
\begin{eqnarray}
x_{n-2} =& \frac{(-1 - ((1 * 2) + (-2 * 1))}{1} \nonumber \\  
x_{n-2} =& \frac{-1}{1} \nonumber \\ 
x_{2} =& -1 \nonumber \\ 
\end{eqnarray}
<br>
<br>
<br>
\begin{eqnarray}
x_{n-3} =& \frac{-10 - ((4 * -1) + (-5 * 2) + (1 * 1))}{3} \nonumber \\ 
x_{x-3} =& \frac{-10 - (-4 -10 + 1}{3} \nonumber \\ 
x_{n-3} =& \frac{-10 - (-13)}{3} \nonumber \\ 
x_{n-3} =& \frac{-10 + 13)}{3} \nonumber \\ 
x_{n-3} =& \frac{3)}{3} \nonumber \\ 
x_{1} =& 1 \nonumber \\ 
\end{eqnarray}

Logo, <br>
\begin{eqnarray}
x_1 =& 1 \nonumber \\ 
x_2 =& -1 \nonumber \\ 
x_3 =& 2 \nonumber \\ 
x_4 =& 1 \nonumber \\ 
\end{eqnarray}

In [34]:
def sist_lin_tri_sup(A,b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1]/A[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]
    return x

In [35]:
A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
b = np.array([-10, -1, 3, 2])

In [36]:
x = sist_lin_tri_sup(A, b)
x

array([ 1., -1.,  2.,  1.])