**<p>Disciplina:** Métodos Numéricos</p>
**<p>Semestre:** 2020.1</p>
**<p>Aluno:** Jardel Brandon de Araujo Regis</p>
**<p>Mátricula:** 201621250014</p>
**<p>1ª Unidade:** REPRESENTAÇÃO NUMÉRICA E TIPOS DE ERROS</p>

---
# <center>Introdução ao Jupyter Notebook</center>
## <center>Atividade #1</center>
---

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/jarde/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/jarde/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/jarde/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
array = np.zeros((10, 10))
print("%d bytes" % (array.size * array.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x000001D3DDDB8C88>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
array = np.arange(10, 50)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
array = np.arange(50)
array = array[::-1]
array

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
array = np.arange(9)
array = array.reshape(3, 3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
array = np.nonzero([1,2,0,0,4,0])
print(array)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
array = np.eye(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
array = np.random.random((3,3,3))
array

array([[[0.31106282, 0.9097515 , 0.65200851],
        [0.91771944, 0.25516227, 0.18708091],
        [0.72217835, 0.66892098, 0.91522024]],

       [[0.21866956, 0.05521767, 0.38390588],
        [0.52468955, 0.47925116, 0.78786982],
        [0.32633008, 0.90187289, 0.51350345]],

       [[0.86183122, 0.4395843 , 0.87062879],
        [0.19910181, 0.74483763, 0.47520885],
        [0.0359803 , 0.51818603, 0.51854682]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
array = np.random.random((10, 10))
print(array, "\nMinimo =", array.min(), "\nMaximo =", array.max())

[[0.93211269 0.51415973 0.97392825 0.30274774 0.86046914 0.96402029
  0.16814739 0.67114243 0.05968903 0.72776024]
 [0.05049318 0.88847564 0.39036063 0.13925767 0.58696531 0.58065303
  0.70511271 0.62469774 0.62176869 0.48796906]
 [0.78970131 0.82871802 0.11946136 0.64738219 0.53745242 0.67134384
  0.70016139 0.59569434 0.95479789 0.96645534]
 [0.64227857 0.52721534 0.70738784 0.41054438 0.70833452 0.60247343
  0.5691943  0.84223586 0.64641187 0.99799171]
 [0.18313671 0.41724119 0.54954285 0.05935257 0.96251932 0.04452274
  0.39244578 0.90984321 0.25007199 0.29457846]
 [0.34389544 0.13784165 0.09873194 0.67932069 0.67062241 0.72230469
  0.73484678 0.5219508  0.42690956 0.16185606]
 [0.77630813 0.82201998 0.65960626 0.66230087 0.98850402 0.18253188
  0.70536855 0.5701401  0.94082583 0.8026019 ]
 [0.57551562 0.58367742 0.0236092  0.05515707 0.81385592 0.24635618
  0.22427822 0.51721916 0.18513126 0.93265019]
 [0.44164431 0.79852832 0.69925773 0.1836644  0.57310047 0.70052094
  0.40146371

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
array = np.random.random(30)
print(array, "\nMedia =", array.mean())

[0.76044824 0.87465865 0.71998543 0.42100602 0.46119568 0.22342371
 0.31034222 0.42451516 0.62971312 0.90125662 0.74584342 0.89856327
 0.78428115 0.16794092 0.23380889 0.04730462 0.12371258 0.37815428
 0.24410285 0.613404   0.98366419 0.86651611 0.0730176  0.62981412
 0.83704854 0.12872466 0.19392561 0.32700747 0.93220303 0.05079421] 
Media = 0.49954587929586836


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
array = np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
array = np.ones((5,5))
array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)
print(0.3, 3 * 0.1)

nan
False
False
nan
True
False
0.3 0.30000000000000004


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
array = np.diag(1+np.arange(4),k=-1)
print(array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
array = np.zeros((8,8),dtype=int)
array[1::2,::2] = 1
array[::2,1::2] = 1
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
array = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
array = np.random.random((5,5))
array = (array - array.mean()) / (array.std())
array

array([[-1.14989335,  1.60594405,  0.33978746,  1.45611557, -0.39303689],
       [-0.318237  , -1.02926163, -0.02584152,  1.55513808,  0.28958575],
       [ 0.00960881,  0.89376789,  1.49777014, -0.30164739, -0.49015449],
       [-0.51816087,  1.58863175, -0.04639283, -1.16596403, -1.33905   ],
       [-0.54487153, -0.29608446, -2.0513565 , -0.50355748,  0.93716046]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
cor = np.dtype([("r", np.ubyte, 1),
                ("g", np.ubyte, 1),
                ("b", np.ubyte, 1),
                ("a", np.ubyte, 1)])
cor

C:\Users\jarde\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
array = np.dot(np.ones((5,3)), np.ones((3,2)))
array

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
array = np.arange(11)
array[(3 < array) & (array <= 8)] *= -1
array

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z = np.arange(40)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
#Z<Z>Z Illegal expression

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39.])

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\jarde\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\jarde\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
array = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(array)), array))

[-9. -1.  9.  4. 10. -5.  8. -2.  6.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
array1 = np.random.randint(0,10,10)
array2 = np.random.randint(0,10,10)
print(np.intersect1d(array1, array2))

[2 4 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
# Modo ignorando avisos
padrao = np.seterr(all="ignore")
array = np.ones(1) / 0
print(array)

# Voltando ao modo normal
_ = np.seterr(**padrao)
array = np.ones(1) / 0
print(array)

[inf]
[inf]


C:\Users\jarde\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: RuntimeWarning: divide by zero encountered in true_divide
  


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\jarde\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2020-06-02 2020-06-03 2020-06-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
array = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
array

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [36]:
array = np.random.uniform(0,10,10)

print (array - array%1)
print (np.floor(array))
print (np.ceil(array)-1)
print (array.astype(int))
print (np.trunc(array))

[3. 5. 4. 4. 6. 4. 8. 3. 3. 9.]
[3. 5. 4. 4. 6. 4. 8. 3. 3. 9.]
[3. 5. 4. 4. 6. 4. 8. 3. 3. 9.]
[3 5 4 4 6 4 8 3 3 9]
[3. 5. 4. 4. 6. 4. 8. 3. 3. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
array = np.zeros((5,5))
array += np.arange(5)
array

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [38]:
def generate():
    for numero in range(10):
        yield numero
array = np.fromiter(generate(),dtype=float,count=-1)
array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [39]:
array = np.linspace(0,1,11,endpoint=False)[1:]
array

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [40]:
array = np.random.random(10)
print("Array Aleatorio:", array)
array.sort()
print("Array organizado:", array)

Array Aleatorio: [0.54530364 0.37175908 0.51517964 0.31359751 0.00496677 0.86895245
 0.48683752 0.79965662 0.25615421 0.57168642]
Array organizado: [0.00496677 0.25615421 0.31359751 0.37175908 0.48683752 0.51517964
 0.54530364 0.57168642 0.79965662 0.86895245]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [41]:
array = np.arange(10)
np.add.reduce(array)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [42]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

print(A, B)

False
False
[1 0 0 0 1] [0 0 1 1 0]


#### 43. Make an array immutable (read-only) (★★☆)

In [43]:
array = np.zeros(10)
array.flags.writeable = False
#array[0] = 1 ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [44]:
array = np.random.random((10,2))
print(array)
coordenadasX, coordenadasY = array[:,0], array[:,1]
coordenadasRho = np.sqrt(coordenadasX**2 + coordenadasY**2)
coordenadasTheta = np.arctan2(coordenadasY, coordenadasX)
print(coordenadasRho)
print(coordenadasTheta)

[[0.37810029 0.84143999]
 [0.59115386 0.16278075]
 [0.4557063  0.06221338]
 [0.27511477 0.45043913]
 [0.54501015 0.19119114]
 [0.60230429 0.41897319]
 [0.75695867 0.13233411]
 [0.05904399 0.02412295]
 [0.9250897  0.51164677]
 [0.53114182 0.90677094]]
[0.92248636 0.61315615 0.4599334  0.52781014 0.57757261 0.73369543
 0.76843916 0.06378173 1.05715342 1.05087828]
[1.14848384 0.26870184 0.13568198 1.02249522 0.33738991 0.6077784
 0.17307433 0.38786293 0.50520329 1.04092006]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [45]:
array = np.random.random((15))
print(array)
array[array.argmax()] = 0
print(array)

[0.92816058 0.12037515 0.3852381  0.53671933 0.10279315 0.68817238
 0.10472056 0.74795694 0.84891867 0.16993012 0.81254867 0.98335646
 0.92087077 0.41207721 0.82239992]
[0.92816058 0.12037515 0.3852381  0.53671933 0.10279315 0.68817238
 0.10472056 0.74795694 0.84891867 0.16993012 0.81254867 0.
 0.92087077 0.41207721 0.82239992]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [46]:
array = np.zeros((5,5), [('x',float),('y',float)])
array['x'], array['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
array

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [47]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [49]:
#Padrao
array = np.zeros((16, 16))
print(array)

#todos os valores
import sys
np.set_printoptions(threshold=sys.maxsize)
array = np.zeros((16, 16))
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
array = np.arange(100)
valor = np.random.uniform(0,100)
print(valor)
index = (np.abs(array - valor)).argmin()
print(array[index])

24.947934775950166
25


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
array = np.zeros(10, [ ('position', [ ('x', float, 1),
                                      ('y', float, 1)]),
                       ('color',    [ ('r', float, 1),
                                      ('g', float, 1),
                                      ('b', float, 1)])])
print(array)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\jarde\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.26525033 0.54973354 0.33485866 0.63536623 0.62793543
  0.36291499 0.23768852 0.07328278 0.73555846]
 [0.26525033 0.         0.54140953 0.28336886 0.73334549 0.47204804
  0.33311155 0.25486504 0.21128743 0.74355796]
 [0.54973354 0.54140953 0.         0.25862005 0.28612648 0.32113692
  0.21038306 0.73676801 0.58015889 0.20217425]
 [0.33485866 0.28336886 0.25862005 0.         0.46940005 0.30697849
  0.05035165 0.48694552 0.34501317 0.46074434]
 [0.63536623 0.73334549 0.28612648 0.46940005 0.         0.60719004
  0.4215809  0.86407274 0.6914168  0.25259229]
 [0.62793543 0.47204804 0.32113692 0.30697849 0.60719004 0.
  0.30545698 0.72338128 0.6198876  0.45458143]
 [0.36291499 0.33311155 0.21038306 0.05035165 0.4215809  0.30545698
  0.         0.52966258 0.38091016 0.41212499]
 [0.23768852 0.25486504 0.73676801 0.48694552 0.86407274 0.72338128
  0.52966258 0.         0.17310597 0.93434013]
 [0.07328278 0.21128743 0.58015889 0.34501317 0.6914168  0.6198876
  0.38091016 0.173105

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [53]:
array64 = (np.random.rand(10)*100).astype(np.float32)
array32 = array64.view(np.int32)
array32[:] = array64
array

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
from io import StringIO

# Fake file
file = StringIO('''1, 2, 3, 4, 5

                   6,  ,  , 7, 8

                    ,  , 9,10,11''')

array = np.genfromtxt(file, delimiter=",", dtype=np.int)
array

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
array = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(array):
    print(index, value)
    
print("\n    or \n")

for index in np.ndindex(array.shape):
    print(index, array[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8

    or 

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
arrayX, arrayY = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
DigonalMatriz = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
GaussianArray = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
GaussianArray

array([[1.        , 0.59959615, 0.89710407, 0.87691897, 0.61844847,
        0.55431276, 0.77524518, 0.69854274, 0.73322378, 0.84490857],
       [0.59959615, 1.        , 0.86156366, 0.86953091, 0.98813213,
        0.95033224, 0.60465446, 0.93493683, 0.91134825, 0.90058013],
       [0.89710407, 0.86156366, 1.        , 0.98984029, 0.86925549,
        0.81068617, 0.79318072, 0.91121469, 0.92473481, 0.98609718],
       [0.87691897, 0.86953091, 0.98984029, 1.        , 0.89445192,
        0.783384  , 0.71258427, 0.87650742, 0.88465578, 0.99742205],
       [0.61844847, 0.98813213, 0.86925549, 0.89445192, 1.        ,
        0.89467451, 0.55883299, 0.89236859, 0.86962044, 0.92255393],
       [0.55431276, 0.95033224, 0.81068617, 0.783384  , 0.89467451,
        1.        , 0.69544335, 0.97023119, 0.95070319, 0.81489096],
       [0.77524518, 0.60465446, 0.79318072, 0.71258427, 0.55883299,
        0.69544335, 1.        , 0.81005228, 0.84692101, 0.70295964],
       [0.69854274, 0.93493683, 0.9112146

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [57]:
numbers = 10
product = 3
array = np.zeros((numbers, numbers))
np.put(array, np.random.choice(range(numbers * numbers), product, replace=False), True)
array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [58]:
lines = np.random.rand(5, 10)

columns = lines - lines.mean(axis=1, keepdims=True)
columns

array([[ 0.23852011,  0.28744874, -0.24082129,  0.25168236, -0.17504381,
         0.12845107,  0.14341585, -0.41531321, -0.1498771 , -0.06846272],
       [-0.23517676, -0.26414892,  0.51307383, -0.1487228 , -0.0077404 ,
         0.28272895, -0.11131286,  0.01926421, -0.23699228,  0.18902703],
       [-0.22185769,  0.16406348, -0.0541397 , -0.20579412, -0.13824238,
        -0.18762107,  0.06001704,  0.20861139,  0.37923689, -0.00427384],
       [-0.3746386 ,  0.48551558,  0.01163839,  0.37715674,  0.06526435,
        -0.26369339,  0.05607427, -0.14152438, -0.08806111, -0.12773184],
       [-0.45308696, -0.24568331, -0.44349413,  0.05774212,  0.43611826,
         0.10438459,  0.41006053,  0.05347047,  0.37674995, -0.29626152]])

#### 59. How to sort an array by the nth column? (★★☆)

In [59]:
array = np.random.randint(0,10,(3,3))
print("Array desordenado\n", array)
nth = 1
print("Array ordenado pela n-ésima coluna:\n", array[array[:, nth].argsort()])

Array desordenado
 [[9 4 9]
 [5 6 1]
 [9 2 5]]
Array ordenado pela n-ésima coluna:
 [[9 2 5]
 [9 4 9]
 [5 6 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [60]:
array = np.random.randint(0,3,(3,10))
print(array)
print((~array.any(axis=0)).any())

[[2 0 1 2 2 1 0 0 1 1]
 [2 0 1 1 2 2 2 2 1 2]
 [0 2 1 0 0 1 1 0 2 0]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [61]:
nearest = 0.5
print(array)
index = array.flat[np.abs(array - nearest).argmin()]
print(index)

[[2 0 1 2 2 1 0 0 1 1]
 [2 0 1 1 2 2 2 2 1 2]
 [0 2 1 0 0 1 1 0 2 0]]
0


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [62]:
arrayA = np.arange(3).reshape(3,1)
arrayB = np.arange(3).reshape(1,3)
iterator = np.nditer([A,B,None])
for x,y,z in iterator: z[...] = x + y
print(iterator.operands[2])

[1 0 1 1 1]


#### 63. Create an array class that has a name attribute (★★☆)

In [63]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

array = NamedArray(np.arange(10), "range_10")
print(array.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [64]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[3. 1. 2. 2. 1. 4. 4. 6. 3. 4.]
[ 5.  1.  3.  3.  1.  7.  7. 11.  5.  7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [65]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
F

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [66]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [67]:
arrayA = np.random.randint(0,10,(3,4,3,4))
sum = arrayA.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[46 51 54 43]
 [68 48 63 50]
 [59 45 61 58]]
2


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [68]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.53159541 0.54406189 0.49060316 0.40751364 0.66941986 0.41222267
 0.51629059 0.51229989 0.54858162 0.54928656]
0    0.531595
1    0.544062
2    0.490603
3    0.407514
4    0.669420
5    0.412223
6    0.516291
7    0.512300
8    0.548582
9    0.549287
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [69]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.1732266 , 0.94209399, 1.39995896, 0.63333448, 1.84004914])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [70]:
array = np.array([1,2,3,4,5])
consecutives_zeros = 3
array_interleaved = np.zeros(len(array) + (len(array)-1)*(consecutives_zeros))
array_interleaved[::consecutives_zeros+1] = array
array_interleaved

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [71]:
arrayA = np.ones((5,5,3))
arrayB = 2*np.ones((5,5))
print(arrayA * arrayB[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [72]:
array = np.arange(25).reshape(5,5)
array[[0,1]] = array[[1,0]]
array

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [73]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
G

array([( 1, 17), ( 1, 60), ( 1, 69), ( 1, 88), ( 2, 36), ( 2, 77),
       (11, 74), (11, 85), (17, 88), (19, 72), (19, 76), (24, 29),
       (24, 55), (29, 55), (30, 60), (30, 77), (36, 77), (40, 57),
       (40, 81), (52, 62), (52, 79), (57, 81), (60, 69), (60, 77),
       (62, 79), (72, 76), (72, 79), (72, 86), (74, 85), (79, 86)],
      dtype=[('p0', '<i4'), ('p1', '<i4')])

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [74]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
A

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [75]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [76]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
array = rolling(np.arange(10), 3)
array

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [77]:
array = np.random.randint(0,2,100)
np.logical_not(array, out=array)

array = np.random.uniform(-1.0,1.0,100)
np.negative(array, out=array)

array([ 0.37925257,  0.75699568, -0.29140896, -0.8900587 , -0.67958179,
        0.87836146,  0.56380815,  0.4872986 , -0.36741822,  0.68318095,
        0.97473981, -0.38511868, -0.21653114,  0.79826421, -0.61084492,
        0.06721799,  0.82440772, -0.90066348, -0.1109313 ,  0.91585513,
       -0.84050864, -0.38112829,  0.35893969,  0.05958961,  0.1511464 ,
       -0.05728778, -0.09937961, -0.90056772, -0.8248786 , -0.06914532,
        0.46422145, -0.29940953,  0.76397159, -0.70410143,  0.629811  ,
       -0.85563624, -0.51268748, -0.08812667,  0.34777046,  0.25642671,
        0.54437288, -0.81029402, -0.13650208,  0.01404747,  0.22665097,
        0.92816005,  0.79144714, -0.01985589, -0.89317787, -0.66836838,
       -0.81167545, -0.60038017,  0.28319323,  0.13384414, -0.49619969,
       -0.27889587, -0.32498759,  0.83332015, -0.0315045 ,  0.22135814,
       -0.21618653,  0.2068509 ,  0.27018166, -0.59835876,  0.53782903,
       -0.58691293,  0.92398122,  0.58765822,  0.37794677, -0.24

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [78]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[2.58039594 4.92689678 3.19035265 8.34852515 2.36073779 7.35920041
 5.36221967 5.86884931 6.32716743 4.72398802]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [79]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.97350825  8.38780597 11.84192983  2.24215067  0.31173917  2.79072041
   2.58550716  5.47312936  2.31562694  6.91987602]
 [ 7.00357118 12.34141099 18.30830989  5.40610927  7.37860807  8.63983766
   4.01099717 10.00763539  8.3149379  15.00398427]
 [14.50617382  9.17554982  1.3113419  11.00917373 10.97519449 11.84223451
  15.37689107 11.39109362 11.98902797  1.21163722]
 [ 0.96481452  6.31312693 12.35196568  0.06309777  1.64309399  2.56647713
   1.90815703  3.91567748  2.26209449 10.2484025 ]
 [ 0.74737532  4.6322297   9.64740322  3.11631444  1.30376855  0.11224135
   4.66534724  1.99721155  0.25314234  6.89801013]
 [ 6.61503679  1.12924852  0.41676922 13.95006051 11.35339165  8.27109802
  14.07398018  4.57022621  8.84303989  4.50909558]
 [ 3.25047373  8.62352781 13.57698401  0.39846493  2.47550052  4.1231169
   0.76124     6.02770117  3.74324844 10.01933689]
 [ 1.45494652  3.85235864 11.58633736  0.57863366  1.45259119  1.3014891
   2.55806068  1.7797385   1.11196913 11.5380288 ]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [80]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 7 3 4 3 4 9 5 1 9]
 [1 1 1 9 8 5 9 3 9 3]
 [6 4 5 2 0 1 2 9 7 5]
 [9 4 7 4 7 1 4 8 3 9]
 [0 5 4 3 6 3 7 4 9 4]
 [2 8 8 5 5 8 0 4 5 4]
 [5 0 6 3 5 5 5 1 5 6]
 [2 3 4 9 6 6 6 8 1 8]
 [0 7 1 2 8 8 3 4 2 8]
 [9 4 4 0 8 9 8 4 8 7]]
[[0 0 0 0 0]
 [0 9 7 3 4]
 [0 1 1 1 9]
 [0 6 4 5 2]
 [0 9 4 7 4]]


C:\Users\jarde\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [81]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [82]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
rank

10

#### 83. How to find the most frequent value in an array?

In [83]:
array = np.random.randint(0,10,50)
print(np.bincount(array).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [84]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
C

array([[[[4, 3, 2],
         [1, 3, 3],
         [3, 3, 4]],

        [[3, 2, 0],
         [3, 3, 3],
         [3, 4, 4]],

        [[2, 0, 0],
         [3, 3, 3],
         [4, 4, 1]],

        [[0, 0, 0],
         [3, 3, 2],
         [4, 1, 3]],

        [[0, 0, 4],
         [3, 2, 4],
         [1, 3, 0]],

        [[0, 4, 4],
         [2, 4, 2],
         [3, 0, 3]],

        [[4, 4, 4],
         [4, 2, 1],
         [0, 3, 3]],

        [[4, 4, 2],
         [2, 1, 4],
         [3, 3, 2]]],


       [[[1, 3, 3],
         [3, 3, 4],
         [4, 2, 1]],

        [[3, 3, 3],
         [3, 4, 4],
         [2, 1, 2]],

        [[3, 3, 3],
         [4, 4, 1],
         [1, 2, 1]],

        [[3, 3, 2],
         [4, 1, 3],
         [2, 1, 2]],

        [[3, 2, 4],
         [1, 3, 0],
         [1, 2, 2]],

        [[2, 4, 2],
         [3, 0, 3],
         [2, 2, 4]],

        [[4, 2, 1],
         [0, 3, 3],
         [2, 4, 1]],

        [[2, 1, 4],
         [3, 3, 2],
         [4, 1, 3]]],


    

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [85]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8 13 16  6 11]
 [13  1  4  8  1]
 [16  4  2 42 12]
 [ 6  8 42  4  2]
 [11  1 12  2  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [86]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [87]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
S

array([[16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.],
       [16., 16., 16., 16.]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [88]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

array = np.random.randint(0,2,(50,50))
for i in range(100): array = iterate(array)
array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

#### 89. How to get the n largest values of an array (★★★)

In [89]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9996 9997 9998 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [90]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [91]:
array = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
result = np.core.records.fromarrays(array.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
result

rec.array([(b'Hello', 2.5, 3), (b'World', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [92]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.63 s ± 59.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
618 ms ± 93.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
369 ms ± 11.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [93]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [94]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 3 1]
 [2 1 2]
 [1 1 0]
 [1 4 3]
 [3 0 0]
 [1 2 2]
 [0 0 2]
 [0 1 3]
 [4 3 2]
 [3 3 0]]
[[0 3 1]
 [2 1 2]
 [1 1 0]
 [1 4 3]
 [3 0 0]
 [1 2 2]
 [0 0 2]
 [0 1 3]
 [4 3 2]
 [3 3 0]]
[[0 3 1]
 [2 1 2]
 [1 1 0]
 [1 4 3]
 [3 0 0]
 [1 2 2]
 [0 0 2]
 [0 1 3]
 [4 3 2]
 [3 3 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [95]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [96]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]
[[0 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [97]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.26346942, 0.09524704, 0.12873494, 0.25213505, 0.2086017 ,
        0.38303073, 0.09339118, 0.02780468, 0.39212801, 0.37056515],
       [0.27743275, 0.10029494, 0.13555763, 0.26549768, 0.21965716,
        0.40333057, 0.09834072, 0.02927827, 0.41290998, 0.39020433],
       [0.2940438 , 0.10630001, 0.14367402, 0.28139413, 0.23280894,
        0.42747963, 0.10422879, 0.03103128, 0.4376326 , 0.41356748],
       [0.49088609, 0.17746063, 0.23985399, 0.46976833, 0.38865866,
        0.71364813, 0.17400286, 0.05180461, 0.73059782, 0.69042273],
       [0.4866996 , 0.17594716, 0.23780841, 0.46576193, 0.38534401,
        0.70756182, 0.17251889, 0.0513628 , 0.72436696, 0.6845345 ],
       [0.49377842, 0.17850624, 0.24126722, 0.47253623, 0.39094866,
        0.71785299, 0.17502809, 0.05210985, 0.73490254, 0.69449074],
       [0.46944184, 0.1697083 , 0.22937602, 0.4492466 , 0.37168019,
        0.68247256, 0.16640158, 0.04954154, 0.69868181, 0.66026176],
       [0.23074216, 0.08341579, 0.1127439

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [98]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [99]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [100]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.20723551  0.1900267 ]
